[package]
name = "fmi"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.8"
url = "2"

[dev-dependencies]
rstest = "0.26.1"
reqwest = { version = "0.12", features = ["blocking"] }
sha2 = "0.10"
zip = "2.2"
tempfile = "3.14"