language: python

matrix:
  include:
    - os: linux
      env:
        - PYTHON_VERSION=2.7
        - MINICONDA=Miniconda2-latest-Linux-x86_64.sh

    - os: linux
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA=Miniconda3-latest-Linux-x86_64.sh

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
        - MINICONDA=Miniconda2-latest-MacOSX-x86_64.sh

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh

install:
  # download and install miniconda
  - wget https://repo.continuum.io/miniconda/$MINICONDA -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # useful for debugging any issues with conda
  - conda info -a

  # install dependencies
  - conda create -q -n test-env python=$PYTHON_VERSION numpy lxml pathlib requests dask
  - source activate test-env
  - python setup.py install

  # build and install the Python wheel
  - python setup.py bdist_wheel --universal
  - |
    for f in dist/FMPy-*.whl; do
      pip install $f
    done

script:
  - cd tests
  - python -m unittest discover
  - cd ..

deploy:
  provider: pypi
  user: t-sommer
  password:
    secure: H4EFw/NtTmmFLOB2yjP8d3uqsPDCzG4WV7RbeEu3rRwz39cZxKkBEvBokKYVPo7tLRwWTQjYGbrwOaLME3hBNo0Mjc9d99Ivcy6UTeE4T6AUln//STDOjy2geJnkBCStZ5I21N+bVom6lzT0Oe0EUnJNBQWnJza7EuMSoTdaH3us5Obtc3F1dqbUensdvaUUvZw9Px7lIQ2C1drwgZvh3yArXX8rVAtxq9wpa601G6tKtrwRcgS4v1jAK8p7MJdFVA/9i5ZAXB/L4waE3pv+k52bjFJ9lcaYOwYcxBedqriKYV78q0+VmBn1TfMK0oNEDgg7abVjZwnx17oGvm389BeEFzN7GXX3RsoNNUlcMFXEEaFVuCWwXNG3Sx6HHsz9zyOE6jbhMt1ag4VHZsCoWO/UoXL7jbd46kBIOuixVgkPZlQSP6FA0/jch85940tYtPQXBxldOiwjYyFFUxv/47iTaB0aAt6Elm+2c/dxgDd0jS/FwmGdChrYcjLU8qjy2/ApMps1C2u00nxN6P/OxqbY0fIqgBFHQOsEgEoSe6sGDzPTOtQrsp/3pP3At1KR8czBkTUxWb+5Xa+ObM/qc4Jcy3QAoLRlGIyId9frOpViI/VgM4RpT+i0chaOwY4yFAexkWwGtWST58VKgvnzYTtnTQ/g+fRgFal3NtkEWUo=
  distributions: bdist_wheel --universal
  skip_cleanup: true
