build: false

environment:

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64

    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64

init:
  - echo %PYTHON_VERSION% %MINICONDA%

install:
  - git submodule update --init --recursive
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env -c anaconda python=%PYTHON_VERSION% dask lxml matplotlib numpy pathlib pyqt pyqtgraph pywin32 requests
  - activate test-env

  # build the wheel
  - python setup.py bdist_wheel --universal

  # install the wheel
  - for %%f in (dist\FMPy-*.whl) do pip install %%f --no-deps

test_script:
  - cd tests
  - python -m unittest discover

artifacts:
  # archive the generated wheel in the build report
  - path: dist\*
